### ISSUE TITLE
Cannot Run Tests

### ISSUE THREAD

**Issue by sshaw** [serch/gistory#5]
After `bundle install`ing: 
```
tmp/gistory >rake
/Users/sshaw/.rvm/rubies/ruby-2.5.2/bin/ruby -I/Users/sshaw/.rvm/gems/ruby-2.5.2/gems/rspec-core-3.9.2/lib:/Users/sshaw/.rvm/gems/ruby-2.5.2/gems/rspec-support-3.9.3/lib /Users/sshaw/.rvm/gems/ruby-2.5.2/gems/rspec-core-3.9.2/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb

An error occurred while loading spec_helper.
Failure/Error: require "pry"

NameError:
  uninitialized constant Pry::Command::ExitAll
# /Users/sshaw/.rvm/gems/ruby-2.5.2/gems/pry-byebug-3.7.0/lib/pry-byebug/commands/exit_all.rb:7:in `<module:PryByebug>'
# /Users/sshaw/.rvm/gems/ruby-2.5.2/gems/pry-byebug-3.7.0/lib/pry-byebug/commands/exit_all.rb:3:in `<top (required)>'
# /Users/sshaw/.rvm/gems/ruby-2.5.2/gems/pry-byebug-3.7.0/lib/pry-byebug/commands.rb:12:in `require'
# /Users/sshaw/.rvm/gems/ruby-2.5.2/gems/pry-byebug-3.7.0/lib/pry-byebug/commands.rb:12:in `<top (required)>'
# /Users/sshaw/.rvm/gems/ruby-2.5.2/gems/pry-byebug-3.7.0/lib/pry-byebug/cli.rb:5:in `require'
# /Users/sshaw/.rvm/gems/ruby-2.5.2/gems/pry-byebug-3.7.0/lib/pry-byebug/cli.rb:5:in `<top (required)>'
# /Users/sshaw/.rvm/gems/ruby-2.5.2/gems/pry-0.13.1/lib/pry/plugins.rb:55:in `require'
# /Users/sshaw/.rvm/gems/ruby-2.5.2/gems/pry-0.13.1/lib/pry/plugins.rb:55:in `load_cli_options'
# /Users/sshaw/.rvm/gems/ruby-2.5.2/gems/pry-0.13.1/lib/pry/cli.rb:40:in `each'
# /Users/sshaw/.rvm/gems/ruby-2.5.2/gems/pry-0.13.1/lib/pry/cli.rb:40:in `add_plugin_options'
# /Users/sshaw/.rvm/gems/ruby-2.5.2/gems/pry-0.13.1/lib/pry/cli.rb:134:in `<top (required)>'
# /Users/sshaw/.rvm/gems/ruby-2.5.2/gems/pry-0.13.1/lib/pry.rb:78:in `require'
# /Users/sshaw/.rvm/gems/ruby-2.5.2/gems/pry-0.13.1/lib/pry.rb:78:in `<top (required)>'
# ./spec/spec_helper.rb:31:in `require'
# ./spec/spec_helper.rb:31:in `<top (required)>'
No examples found.
No examples found.


Finished in 0.00022 seconds (files took 0.87462 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples

Finished in 0.00022 seconds (files took 0.87462 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples


```

**Comment by serch** [comment]
hi @sshaw thanks for reporting, it seems there is an issue with pry 0.13.1 and pry-byebug 3.7.0
latest master is now using pry-byebug 3.9.0 and it should work
please reopen if you are still experiencing issues
